title = "Ravi Sagar Hugo website"
baseURL = "https://www.ravi.pro/hugo/"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"
publishDir = "docs"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Atlassian Consultant and Drupal expert. Author of Mastering Jira 7. Technologist and problem solve. Loves DevOps."
  facebook = ""
  twitter = "https://twitter.com/ravisagar"
  instagram = ""
  youtube = ""
  github = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
